version: "3.8"

services:
  postgres:
    image: postgres:14.4
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: [ "./wait_for_postgres.sh", "./publicnotes/manage.py", "runserver", "0.0.0.0:8000" ]
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data: