# Generated by Django 3.0.2 on 2022-05-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20220511_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='Публичный e-mail'),
        ),
    ]
