# Generated by Django 3.0.2 on 2022-05-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_auto_20220503_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nickname',
            field=models.CharField(max_length=150, unique=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
    ]
