# Generated by Django 3.1.14 on 2022-06-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_auto_20220605_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
