# Generated by Django 3.0.2 on 2022-05-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_auto_20220503_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title', 'color'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default=1, max_length=6, verbose_name='Код цвета'),
            preserve_default=False,
        ),
    ]
