# Generated by Django 3.1.14 on 2022-05-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_auto_20220515_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер'),
        ),
        migrations.AddField(
            model_name='category',
            name='preview',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
