# Generated by Django 3.1.14 on 2022-06-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_note_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичная'),
        ),
    ]
