# Generated by Django 3.1.14 on 2022-05-26 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_auto_20220526_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner',
        ),
    ]
