# Generated by Django 3.0.2 on 2022-05-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0007_author_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
