# Generated by Django 3.1.14 on 2022-06-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_auto_20220608_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_pined',
            field=models.BooleanField(default=False, verbose_name='Закреплена в профиле'),
        ),
    ]
