# Generated by Django 3.1.14 on 2022-06-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0011_auto_20220609_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='rating',
        ),
    ]
