# Generated by Django 3.1.14 on 2022-06-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0012_remove_note_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
