# Generated by Django 3.1.14 on 2022-07-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0013_remove_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
